services:
  backend:
    container_name: be-walmart-backend-container
    image: be-walmart-backend-image
    build:
      context: ./be-walmart-palindromo
    ports:
      - "3000:3000"

  fronted:
    container_name: fe-walmart-backend-container
    image: fe-walmart-backend-image
    build:
      context: ./fe-walmart-palindromo
    ports:
      - "3001:3001"

  mongo:
    environment:
      - MONGO_INITDB_ROOT_USERNAME=productListUser
      - MONGO_INITDB_ROOT_PASSWORD=productListPassword
    ports:
      - '27017:27017'
    container_name: db-walmart-container
    volumes:
      - './db-walmart-palindromo:/database'
    image: 'mongo:3.6.8'

networks:
  default:
  
