services:
  backend:
    container_name: be-buscador-palindromo-container
    image: be-buscador-palindromo-image
    build:
      context: ./be-buscador-palindromo
    ports:
      - "3000:3000"

  fronted:
    container_name: fe-buscador-palindromo-container
    image: fe-buscador-palindromo-image
    build:
      context: ./fe-buscador-palindromo
    ports:
      - "3001:3001"

  mongo:
    environment:
      - MONGO_INITDB_ROOT_USERNAME=productListUser
      - MONGO_INITDB_ROOT_PASSWORD=productListPassword
    ports:
      - '27017:27017'
    container_name: db-buscador-container
    volumes:
      - './db-buscador-palindromo:/database'
    image: 'mongo:3.6.8'

networks:
  default:
  
